monolog:
    channels: ["http_plug", "processing", "configuration"]
    handlers:
        stdout:
            type: stream
            path: php://stdout
            level: debug
            channels: ["!event", "!request", "!lock", "!php"]
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]